// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKrYlixHJHH9pEXWcoqwQokZ9nUZ8MjWA',
    appId: '1:60293210629:web:948446a0dcaf3eb245f26c',
    messagingSenderId: '60293210629',
    projectId: 'socialtravel-3f975',
    authDomain: 'socialtravel-3f975.firebaseapp.com',
    storageBucket: 'socialtravel-3f975.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmnviEbvogooeZZJDm3_04cnjU6ITzibI',
    appId: '1:60293210629:android:b3ffbf19715794b245f26c',
    messagingSenderId: '60293210629',
    projectId: 'socialtravel-3f975',
    storageBucket: 'socialtravel-3f975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjMuynNdkSDUFBdLvnMRxJUPJi8D_TJ5Q',
    appId: '1:60293210629:ios:e90c886d0f0995e145f26c',
    messagingSenderId: '60293210629',
    projectId: 'socialtravel-3f975',
    storageBucket: 'socialtravel-3f975.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjMuynNdkSDUFBdLvnMRxJUPJi8D_TJ5Q',
    appId: '1:60293210629:ios:e90c886d0f0995e145f26c',
    messagingSenderId: '60293210629',
    projectId: 'socialtravel-3f975',
    storageBucket: 'socialtravel-3f975.appspot.com',
    iosBundleId: 'com.example.travel',
  );
}
